// This file is generated by Slice Machine. Update with care!

import PostSpaceTraveling from './PostSpaceTraveling';

export {
	PostSpaceTraveling,
};

export const components = {
	post_space_traveling: PostSpaceTraveling,
};
